# Generated by Django 3.2.4 on 2021-06-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube', '0002_auto_20210616_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videodetail',
            name='default_thumbnail',
        ),
        migrations.RemoveField(
            model_name='videodetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videodetail',
            name='medium_thumbnail',
        ),
        migrations.RemoveField(
            model_name='videodetail',
            name='publishedAt',
        ),
        migrations.RemoveField(
            model_name='videodetail',
            name='title',
        ),
        migrations.AddField(
            model_name='videodetail',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
